apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-backend
          # CHANGE THIS LINE BELOW!
          image: aymensat/devops-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
