apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 80 # We will access port 80
      targetPort: 5000 # It forwards to container port 5000
  type: ClusterIP
